name: Dart

on:
  push:
    branches: [ master, dart ]
  pull_request:
    branches: [ master, dart ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dart
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: 安装依赖
        run: dart pub get

      - name: 执行
        run: dart bin/whisper.dart
